# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(verbose_name='%B %d %Y'),
        ),
    ]
