# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20170630_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(verbose_name='%B %d %Y'),
        ),
    ]
